# Generated by Django 2.2 on 2019-04-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
